apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-customer-deployment
  namespace: packapp04
spec:
  selector:
    matchLabels:
      app: back-customer
  replicas: 1
  template:
    metadata:
      labels:
        app: back-customer
    spec:
      containers:
      - name: back-customer
        image: registry.hackathon-container.com/packapp04/back-customer:2.2
        ports:
        - containerPort: 9091
      imagePullSecrets:
      - name: registry
---
apiVersion: v1
kind: Service
metadata:
  name: back-customer-svc
  namespace: packapp04
spec:
  type: ClusterIP
  selector:
    app: back-customer
  ports:
  - name: back-customer-ports 
    port: 9091
    targetPort: 9091
    protocol: TCP
